### ISSUE TITLE
RxJava2 Support

### ISSUE THREAD

**Issue by jossiwolf** [manas-chaudhari/android-mvvm#41]
Hello,
are you planning to add RxJava2 support? If yes, any ETA yet?

**Comment by manas-chaudhari** [comment]
Yes, its on my list. I'll try to finish it over this weekend. Worst case: next week.

**Comment by manas-chaudhari** [comment]
@jossiwolf I am prioritizing #40 over this. 
With this new structure, Rx support would be separated into a separate module. After that, it would be easy to add another module for rxjava2 support. What do you think?

**Comment by jossiwolf** [comment]
@manas-chaudhari
Sounds like a good move. Having a structured codebase is important.
Take your time!

**Comment by tvaamorim** [comment]
Hey @manas-chaudhari thanks for the project. I'm starting now with Rx and MVVM. Seen your video at Droid Connin do you use a converter from ObservableField to Observable. Here it is at file "FieldUtils". How can I convert it to the rx2? 

any ETA to this project with rx2?

Thanks

**Comment by manas-chaudhari** [comment]
@tvaamorim Yes, you are right about `FieldUtils`.

I have started working on RxJava 2 support. The plan is to primarily support only RxJava 2, with an optional module to support RxJava 1 via [RxJava2Interop](https://github.com/akarnokd/RxJava2Interop). My target is to complete this by March 5th.

Until then, I recommend that you create your own wrapper over `FieldUtils` using [RxJava2Interop](https://github.com/akarnokd/RxJava2Interop). This wrapper would convert between `rx2.Observable` <-> `databinding.ObservableField`. For working with RecyclerView/ViewPager, you can add a BindingConversion for `rx2.Observable` -> `rx1.Observable`.

**Comment by tvaamorim** [comment]
@manas-chaudhari thanks for the fast response.

I will take a look at RxJava2Interop.

Thanks. Please keep with this awesome project. It helped me a lot ;D

**Comment by bigmikehoncho** [comment]
Hey @manas-chaudhari great job so far and thanks for the library.

@tvaamorim I have forked this library and built an [RxJava2 version](https://github.com/bigmikehoncho/android-mvvm) that you may use in the meantime. Feel free to check it out.

**Comment by tvaamorim** [comment]
@bigmikehoncho awesome man!! exactly what I need! 
Checking the project right now =D

Thanks for sharing it.

**Comment by manas-chaudhari** [comment]
RxJava2 support has been released :)
Do note the maven coordinate changes as mentioned in [changelog](https://github.com/manas-chaudhari/android-mvvm/blob/master/CHANGELOG.md)
