### ISSUE TITLE
How to reuse layouts?

### ISSUE THREAD

**Issue by szantogab** [manas-chaudhari/android-mvvm#45]

**Comment by szantogab** [comment]
How can we cleanly use a given layout XML to be used with multiple ViewModels? Do we need to create an abstract ViewModel for that layout containing the ObservableField<String>s?? But that way I can't directly bind the data back to the model (for example the User model)

**Comment by manas-chaudhari** [comment]
Creating an abstract ViewModel should work. Can you provide more details about why you cannot bind data back to the model?

For example:
```java
public abstract class CommonViewModel {
        public final ObservableField<String> name;

        protected CommonViewModel() {
            name = getNameField();
        }

        protected abstract ObservableField<String> getNameField();
}
```

You could also create CommonViewModel as an interface. 
```java
public interface CommonViewModel {
     ObservableField<String> getName();
}

class UserViewModel implements CommonViewModel {
    public final ObservableField<String> name; // Initialize in constructor
    

    @Override
    public ObservableField<String> getName() {
        return name;
    }
}
```

**Comment by szantogab** [comment]
Yes that is what I thought in the first place, but imagine that we're displaying a user's profile:

```
 public class UserDetailViewModel {
        public final ObservableField<User> user;
}

```

And then in the layout we have:

```
<EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@={vm.user.name}" />

```

I think this is the most boilerplate-free code, because it eliminates having a `toObservable` and `toField` conversion between the ViewModel's fields and the Model's fields just to have two-way binding.

What do you think?

**Comment by manas-chaudhari** [comment]
I am not understanding which boilerplate are you talking about. Can you share the code which has boilerplate?

**Comment by szantogab** [comment]
Consider a layout representing a User's profile:

```
<EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@={vm.firstName}" />
<EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@={vm.lastName}" />
<EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@={vm.nickName}" />
<EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:text="@={vm.username}" />
```

Now in the ViewModel we have:
```
 public class UserDetailViewModel {
        public final ObservableField<String> firstName = new ObservableField<>();
        public final ObservableField<String> lastName = new ObservableField<>();
        public final ObservableField<String> nickName = new ObservableField<>();
        public final ObservableField<String> username = new ObservableField<>();
}
```

Now, assume that the user modifies his/her nickname, and we'd like to save the modified User object on a backend. We need to convert this ViewModel to a User object somehow:

```
public void save() {
      User user = new User();
      user.nickName = nickName.get();
      user.lastName = lastName.get();
      user.username = username.get();
      userService.saveUser(user).subscribe(.....);
}
```

This is the boilerplate code, because we need to wire up every property from the ViewModel to the Model and vica-versa.

**Comment by szantogab** [comment]
> I am curious about why you need to use a single layout with two ViewModels. Can you also share your usecase

Sure, I have a layout: ![Uploading row copy 2.png…]()
This layout can contain a user with his name and profile picture, but it can also contain a product. So this layout should be reused.

**Comment by manas-chaudhari** [comment]
If you simply want to capture form inputs into your model, your way of using `vm.user.name` is great.

So I suppose the reuse issue comes up when you want to display `vm.user.name` in one case and `vm.product.name` in other case. Did I get it right?

In that case, one way is to use `setters` in the CommonViewModel instead of `ObservableField`.
```java
interface CommonViewModel {
    public String getName();
    public void setName(String name);
}

public UserViewModel implements CommonViewModel {
    ...
    @Override
    public void setName(String name) {
        this.user.name = name;
    }
}

//Similarly for ProductViewModel
```

**Comment by szantogab** [comment]
Yes, this is what I would like to achieve. Will it work with two-way binding ?

**Comment by manas-chaudhari** [comment]
Yes, it will. Wwo-way binding invokes the setter. 

If you also intend to invoke this setter programmatically, you'll also need to setup Observation as described in the [Data Binding Documentation](https://developer.android.com/topic/libraries/data-binding/index.html#observable_objects). Note that you'll have to make `CommonViewModel` extend `databinding.Observable` and declare `@Bindable` in the getter.

**Comment by manas-chaudhari** [comment]
@szantogab Can you close the issue if your query has been resolved?
