### ISSUE TITLE
What is BR in the initialization of Application object

### ISSUE THREAD

**Issue by harica** [manas-chaudhari/android-mvvm#62]
in getting started, initializing the library in the applicaiton object following statement is used:
viewDataBinding.setVariable(BR.vm, viewModel);

What is BR in the above statement; I am new to Java. I am unable to fix BR when I try to do it in a new project. Any help will be appreciated...

**Comment by manas-chaudhari** [comment]
`BR` is a class generated automatically by the compiler. It contains field corresponding to every data binding variable name defined in the xml's `<data>` tag.
